---
# handlers file for server

#- name: Reload Apache
#  service:
#    name: apache2
#    state: reloaded

- name: Restart Apache
  service:
    name: apache2
    state: restarted

- name: Restart ufw
  service:
    name: ufw
    state: restarted